# Generated by Django 5.1.2 on 2024-12-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('class_name', models.IntegerField()),
            ],
        ),
    ]
